baseURL = 'https://greek-stasia.github.io'
languageCode = 'en-us'
title = 'StaygeLabs'
theme= 'hugo-theme-shell'
[Params]
	description = "StaygeLabs"
	[Params.Terminal]
	scheme = "Molokai"
	userName="user"
	pcName="staygelabs"
	workDir="stayge"
	profile = "profile"
	description = """
	Hi I'm Anastasia!
	My friends call me Stayge
	"""
	[Params.Tree]
  	use = true
 	 folderName = "my_activity"
  	# Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  	files = [ 
    	["Write Ups", "https://www.example.com/"],
    	["Interests", "https://www.example.com/"],
    	["Go", "https://golang.org/"],
    	["Hugo", "/post/some-activity.md"],
    	["Docker", "/post/some-activity.md"],
  	]
